export const DISEASE_INFO = {
  'Tomato___Late_blight': {
    name: 'Late Blight',
    crop: 'Tomato',
    nameTE: 'లేట్ బ్లైట్',
    severity: 'high',
    description: 'Caused by Phytophthora infestans, a water mold that thrives in cool, wet conditions.',
    symptoms: ['Dark brown lesions on leaves', 'White fuzzy growth on undersides', 'Rapid plant collapse'],
    organic: ['Copper-based fungicide spray', 'Neem oil application every 7 days', 'Remove infected plant parts immediately'],
    chemical: ['Mancozeb 75% WP @ 2.5g/L', 'Metalaxyl + Mancozeb @ 2g/L', 'Cymoxanil + Mancozeb'],
    prevention: ['Use certified disease-free seeds', 'Maintain proper plant spacing', 'Avoid overhead irrigation'],
    spreadRisk: 85,
    recoveryDays: 14,
    color: '#ef4444',
  },
  'Tomato___Early_blight': {
    name: 'Early Blight',
    crop: 'Tomato',
    nameTE: 'ఎర్లీ బ్లైట్',
    severity: 'medium',
    description: 'Caused by Alternaria solani fungus affecting lower leaves first.',
    symptoms: ['Concentric ring lesions', 'Yellow halo around spots', 'Premature leaf drop'],
    organic: ['Neem oil + garlic spray', 'Baking soda solution (1 tbsp/L)', 'Compost tea spray'],
    chemical: ['Mancozeb @ 2g/L water', 'Azoxystrobin @ 1ml/L', 'Chlorothalonil 75% WP'],
    prevention: ['Crop rotation every 3 years', 'Mulching to prevent soil splash', 'Remove plant debris after harvest'],
    spreadRisk: 55,
    recoveryDays: 10,
    color: '#f97316',
  },
  'Tomato___Leaf_Miner': {
    name: 'Leaf Miner',
    crop: 'Tomato',
    nameTE: 'లీఫ్ మైనర్',
    severity: 'medium',
    description: 'Larvae of flies that tunnel through leaf tissue creating silvery trails.',
    symptoms: ['Serpentine tunnels in leaves', 'Silvery white trails', 'Leaf yellowing and drop'],
    organic: ['Yellow sticky traps', 'Neem oil spray', 'Release parasitic wasps (Diglyphus isaea)'],
    chemical: ['Abamectin 1.8% EC @ 0.5ml/L', 'Spinosad 45% SC', 'Cyromazine 75% WP'],
    prevention: ['Install insect nets', 'Destroy crop residues', 'Monitor with sticky traps weekly'],
    spreadRisk: 40,
    recoveryDays: 8,
    color: '#eab308',
  },
  'Tomato___healthy': {
    name: 'Healthy',
    crop: 'Tomato',
    nameTE: 'ఆరోగ్యకరమైన',
    severity: 'none',
    description: 'Your tomato plant appears healthy with no visible signs of disease.',
    symptoms: [],
    organic: ['Continue regular watering schedule', 'Apply compost monthly', 'Maintain mulch layer'],
    chemical: [],
    prevention: ['Monitor weekly for early signs', 'Maintain soil pH 6.0-6.8', 'Ensure good air circulation'],
    spreadRisk: 0,
    recoveryDays: 0,
    color: '#22c55e',
  },
  'Rice___Brown_Spot': {
    name: 'Brown Spot',
    crop: 'Rice',
    nameTE: 'బ్రౌన్ స్పాట్',
    severity: 'high',
    description: 'Caused by Cochliobolus miyabeanus fungus, associated with nutrient-deficient soils.',
    symptoms: ['Oval brown lesions with gray centers', 'Yellow halo around lesions', 'Grain discoloration'],
    organic: ['Potassium silicate spray', 'Trichoderma-based biocontrol', 'Silicon-rich amendments'],
    chemical: ['Iprodione 50% WP @ 1g/L', 'Propiconazole 25% EC @ 1ml/L', 'Carbendazim 50% WP'],
    prevention: ['Balanced NPK fertilization', 'Use resistant varieties', 'Seed treatment with fungicide'],
    spreadRisk: 70,
    recoveryDays: 12,
    color: '#ef4444',
  },
  'Rice___Leaf_Blast': {
    name: 'Leaf Blast',
    crop: 'Rice',
    nameTE: 'లీఫ్ బ్లాస్ట్',
    severity: 'critical',
    description: 'Most destructive rice disease worldwide, caused by Magnaporthe oryzae.',
    symptoms: ['Diamond-shaped lesions', 'Gray center with brown border', 'Stunted growth'],
    organic: ['Silicon spray (potassium silicate)', 'Compost tea application', 'Trichoderma harzianum'],
    chemical: ['Tricyclazole 75% WP @ 0.6g/L', 'Isoprothiolane 40% EC', 'Carbendazim + Mancozeb'],
    prevention: ['Avoid excess nitrogen', 'Use blast-resistant varieties', 'Maintain water level 5cm'],
    spreadRisk: 90,
    recoveryDays: 18,
    color: '#dc2626',
  },
  'Corn___Common_Rust': {
    name: 'Common Rust',
    crop: 'Corn',
    nameTE: 'కామన్ రస్ట్',
    severity: 'medium',
    description: 'Caused by Puccinia sorghi fungus producing brick-red pustules on leaves.',
    symptoms: ['Brick-red oval pustules', 'Pustules turn black at maturity', 'Leaf yellowing around pustules'],
    organic: ['Baking soda spray', 'Neem extract application', 'Garlic-chili extract spray'],
    chemical: ['Propiconazole 25% EC @ 1ml/L', 'Tebuconazole @ 1ml/L', 'Mancozeb 75% WP @ 2g/L'],
    prevention: ['Plant rust-resistant hybrids', 'Early planting to avoid peak rust season', 'Scout fields weekly'],
    spreadRisk: 60,
    recoveryDays: 10,
    color: '#f97316',
  },
  'Potato___Late_blight': {
    name: 'Late Blight',
    crop: 'Potato',
    nameTE: 'లేట్ బ్లైట్',
    severity: 'critical',
    description: 'Same pathogen as tomato late blight, can devastate entire potato crops within days.',
    symptoms: ['Water-soaked dark lesions', 'White sporulation on leaf undersides', 'Foul smell from tubers'],
    organic: ['Copper hydroxide spray', 'Biofungicide with Bacillus subtilis', 'Remove infected plants immediately'],
    chemical: ['Cymoxanil 8% + Mancozeb 64%', 'Dimethomorph 50% WP', 'Propamocarb + Fluopicolide'],
    prevention: ['Use certified seed potatoes', 'Hill up soil around plants', 'Avoid overhead irrigation'],
    spreadRisk: 95,
    recoveryDays: 20,
    color: '#dc2626',
  },
}

export const CROPS = ['Tomato', 'Rice', 'Wheat', 'Corn', 'Potato', 'Cotton', 'Groundnut', 'Soybean']

export const SEVERITY_LABELS = {
  none: { label: 'Healthy', color: '#22c55e', bg: 'bg-forest-950', text: 'text-forest-400', score: 0 },
  low: { label: 'Low Risk', color: '#86efac', bg: 'bg-forest-950', text: 'text-forest-300', score: 25 },
  medium: { label: 'Moderate', color: '#facc15', bg: 'bg-yellow-950', text: 'text-yellow-400', score: 55 },
  high: { label: 'High Risk', color: '#f97316', bg: 'bg-orange-950', text: 'text-orange-400', score: 75 },
  critical: { label: 'Critical', color: '#ef4444', bg: 'bg-red-950', text: 'text-red-400', score: 95 },
}

export const MOCK_HISTORY = [
  { id: 1, crop: 'Tomato', disease: 'Late Blight', severity: 'high', date: '2025-01-10', confidence: 94.2, treated: true },
  { id: 2, crop: 'Rice', disease: 'Brown Spot', severity: 'medium', date: '2025-01-08', confidence: 87.5, treated: true },
  { id: 3, crop: 'Corn', disease: 'Common Rust', severity: 'medium', date: '2025-01-05', confidence: 91.3, treated: false },
  { id: 4, crop: 'Tomato', disease: 'Healthy', severity: 'none', date: '2025-01-03', confidence: 96.8, treated: false },
  { id: 5, crop: 'Potato', disease: 'Late Blight', severity: 'critical', date: '2024-12-28', confidence: 98.1, treated: true },
]
